import type { QuizletSet } from '@/app/api/quizlet-search/route'
import type { FlashcardTerm } from '@/app/api/quizlet-set/route'

export interface PopularSet extends QuizletSet {
  terms: FlashcardTerm[]
}

export const POPULAR_SETS: PopularSet[] = [
  {
    id: 'lsat-lr-core',
    title: 'LSAT Logical Reasoning: Core Concepts',
    termCount: 45,
    author: 'LSATpro_2026',
    terms: [
      { term: 'Assumption', definition: 'An unstated premise that must be true for the argument\'s conclusion to logically follow.' },
      { term: 'Conclusion', definition: 'The main claim or position the argument is trying to establish, supported by the premises.' },
      { term: 'Premise', definition: 'A stated reason or piece of evidence offered in support of the conclusion.' },
      { term: 'Flaw', definition: 'A reasoning error that weakens or invalidates the logical connection between premises and conclusion.' },
      { term: 'Strengthen', definition: 'A piece of evidence or reasoning that makes the conclusion more likely to be true.' },
      { term: 'Weaken', definition: 'A piece of evidence or reasoning that makes the conclusion less likely to be true.' },
      { term: 'Inference', definition: 'A statement that must be true, or is most supported, based solely on the given information.' },
      { term: 'Parallel Reasoning', definition: 'An argument that uses the exact same logical structure as the original stimulus.' },
    ],
  },
  {
    id: 'gre-awa-argument',
    title: 'GRE AWA: Argument Essay Templates & Flaws',
    termCount: 38,
    author: 'GREready_Alex',
    terms: [
      { term: 'Unwarranted Assumption', definition: 'The author assumes X without evidence; this is flawed because alternative explanations exist.' },
      { term: 'Causal Fallacy', definition: 'The argument confuses correlation with causation — X preceding Y does not mean X caused Y.' },
      { term: 'False Analogy', definition: 'The comparison is flawed because the two situations differ in crucial ways the author ignores.' },
      { term: 'Biased Sample', definition: 'The survey or data may be unrepresentative; we need to know how participants were selected.' },
      { term: 'Vague Evidence', definition: 'The evidence cited is too vague to support the conclusion without additional specifics.' },
      { term: 'Alternative Explanation', definition: 'The observed outcome could equally result from another cause the author has not considered.' },
      { term: 'Hasty Generalization', definition: 'The conclusion applies a finding from a small or specific group to a much broader population.' },
      { term: 'Either/Or Fallacy', definition: 'The argument presents only two options when additional alternatives clearly exist.' },
    ],
  },
  {
    id: 'ielts-task2-vocab',
    title: 'IELTS Academic Writing Task 2: Essay Vocabulary',
    termCount: 72,
    author: 'IELTSmaster9',
    terms: [
      { term: 'Outweigh', definition: 'To be greater or more significant than something else; used when comparing advantages and disadvantages.' },
      { term: 'Proliferation', definition: 'A rapid increase in the number or amount of something, often used for technology or social trends.' },
      { term: 'Mitigate', definition: 'To make something less severe, serious, or painful; used when discussing solutions.' },
      { term: 'Exacerbate', definition: 'To make a problem, bad situation, or negative feeling worse.' },
      { term: 'Proponents', definition: 'Supporters of a particular idea, cause, or policy; contrast with "opponents" or "critics".' },
      { term: 'Empirical evidence', definition: 'Evidence based on observation or experience rather than theory or pure logic.' },
      { term: 'Counterbalance', definition: 'To have an equal but opposing effect on something, offsetting it.' },
      { term: 'Contentious', definition: 'Causing or likely to cause disagreement or controversy; a useful adjective for essay topics.' },
    ],
  },
  {
    id: 'toefl-writing-vocab',
    title: 'TOEFL Writing: Academic Vocabulary & Phrases',
    termCount: 60,
    author: 'TOEFLprep_Pro',
    terms: [
      { term: 'Contend', definition: 'To assert or maintain a position; stronger than "say" and used in academic argumentation.' },
      { term: 'Refute', definition: 'To prove that a statement, theory, or claim is wrong by argument or evidence.' },
      { term: 'Substantiate', definition: 'To provide evidence that proves or supports a claim; makes an argument more credible.' },
      { term: 'Corroborate', definition: 'To confirm or give support to a statement, theory, or finding.' },
      { term: 'Concede', definition: 'To acknowledge the validity of an opposing point before countering it; signals nuanced thinking.' },
      { term: 'Posit', definition: 'To suggest or assume something as a fact or as a basis for argument.' },
      { term: 'Infer', definition: 'To reach a conclusion based on evidence and reasoning rather than explicit statement.' },
      { term: 'Assert', definition: 'To state a fact or belief confidently and forcefully, often without proof.' },
    ],
  },
  {
    id: 'act-writing-structure',
    title: 'ACT Writing: Essay Structure & Persuasion',
    termCount: 32,
    author: 'ACTessay_Coach',
    terms: [
      { term: 'Thesis statement', definition: 'A clear, specific claim that states your perspective on the issue, typically at the end of the intro.' },
      { term: 'Topic sentence', definition: 'The first sentence of a body paragraph that introduces and controls the main point of that paragraph.' },
      { term: 'Counterclaim', definition: 'An opposing viewpoint that you acknowledge and then rebut to strengthen your own argument.' },
      { term: 'Rebuttal', definition: 'Your response to the counterclaim that explains why your position is still more convincing.' },
      { term: 'Concession', definition: 'Acknowledging that the opposing argument has some validity before pivoting back to your position.' },
      { term: 'Evidence', definition: 'Specific examples, facts, or logical reasoning that support your claim.' },
      { term: 'Transition', definition: 'Words or phrases that connect ideas between sentences and paragraphs for a cohesive essay.' },
      { term: 'Call to action', definition: 'A closing statement urging readers or society to take a specific step based on your argument.' },
    ],
  },
  {
    id: 'lsat-rc-terms',
    title: 'LSAT Reading Comprehension: Key Question Types',
    termCount: 28,
    author: 'LSATpro_2026',
    terms: [
      { term: 'Primary purpose', definition: 'The main goal or intent of the passage as a whole, not a detail within it.' },
      { term: 'Author\'s attitude', definition: 'The tone or perspective the author takes toward the subject, often subtle (e.g., cautiously optimistic).' },
      { term: 'Inference question', definition: 'A question asking what can be concluded or inferred from information stated in the passage.' },
      { term: 'Explicit detail', definition: 'Information directly and clearly stated in the passage text.' },
      { term: 'Implicit meaning', definition: 'Meaning that is suggested or implied but not directly stated in the passage.' },
      { term: 'Analogy question', definition: 'A question asking you to identify a scenario outside the passage that parallels a relationship within it.' },
      { term: 'Structure question', definition: 'A question about how the passage or an argument within it is logically organized.' },
      { term: 'Weaken/Strengthen (RC)', definition: 'A question asking which answer choice most damages or supports a claim made in the passage.' },
    ],
  },
  {
    id: 'gre-awa-issue',
    title: 'GRE Analytical Writing: Issue Essay Strategies',
    termCount: 41,
    author: 'GREready_Alex',
    terms: [
      { term: 'Nuanced position', definition: 'A thesis that acknowledges conditions under which the opposing view could be valid, showing complexity.' },
      { term: 'Qualifying language', definition: 'Words like "often," "generally," or "in many contexts" that add precision and avoid overstatement.' },
      { term: 'Abstract principle', definition: 'A broad general rule or truth used to support a specific claim or example in the essay.' },
      { term: 'Concrete example', definition: 'A specific, real-world instance that illustrates an abstract argument or principle.' },
      { term: 'Logical chain', definition: 'A series of connected reasons that build step-by-step toward the essay\'s conclusion.' },
      { term: 'Synthesis', definition: 'The act of combining multiple ideas, examples, or perspectives into a coherent unified argument.' },
      { term: 'Scope qualification', definition: 'Limiting your claim to a specific domain (e.g., "in democratic societies") to make it more defensible.' },
      { term: 'Rhetorical question', definition: 'A question asked to create effect or provoke thought, not to elicit a direct answer.' },
    ],
  },
  {
    id: 'ielts-task1-language',
    title: 'IELTS Writing Task 1: Data Description Language',
    termCount: 35,
    author: 'IELTSmaster9',
    terms: [
      { term: 'Dramatic increase', definition: 'A sharp and significant rise in data, e.g., "There was a dramatic increase from 20% to 65%."' },
      { term: 'Slight fluctuation', definition: 'A minor and irregular variation in data over a period of time.' },
      { term: 'Plateau', definition: 'A period where data remains relatively constant after a period of change.' },
      { term: 'Peak', definition: 'The highest point reached by a data value within the given time period.' },
      { term: 'Overall trend', definition: 'The general direction data moves across the entire time period, stated in the overview paragraph.' },
      { term: 'Account for', definition: 'To represent or make up a share of the total, e.g., "Cars accounted for 40% of emissions."' },
      { term: 'Comparatively', definition: 'Used when making a direct comparison between two or more data sets or categories.' },
      { term: 'Marginal change', definition: 'A very small increase or decrease in data, barely noticeable on the graph.' },
    ],
  },
]
